package com.bossbuttonstudios.machinewars.model.economy

/**
 * Tracks the player's two resource types.
 *
 * Ore   — universal in-battle currency; generated by Miners, spent on units
 *         and store purchases. Depletes the treasury (relevant in Resource Hunt).
 *
 * Artifacts — rare post-mission rewards; spent in the upgrade store to unlock
 *             boost machines and research nodes. Never spent in-battle.
 */
class Wallet(
    initialOre: Int = 0,
    initialArtifacts: Int = 0,
) {
    var ore: Int = initialOre
        private set

    var artifacts: Int = initialArtifacts
        private set

    // --- Ore ---

    fun earnOre(amount: Int) {
        require(amount >= 0) { "earnOre amount must be non-negative" }
        ore += amount
    }

    /**
     * Spends [amount] ore.
     * @return true if successful; false if insufficient funds (no state change).
     */
    fun spendOre(amount: Int): Boolean {
        require(amount >= 0) { "spendOre amount must be non-negative" }
        if (ore < amount) return false
        ore -= amount
        return true
    }

    // --- Artifacts ---

    fun earnArtifact() { artifacts++ }

    /**
     * Spends one artifact.
     * @return true if successful; false if none available.
     */
    fun spendArtifact(): Boolean {
        if (artifacts <= 0) return false
        artifacts--
        return true
    }
}
